apiVersion: apps/v1
kind: Deployment
metadata:
  name: manjorno-orders
spec:
  selector:
    matchLabels:
      app: manjorno-orders
  replicas: 1
  template:
    metadata:
      labels:
        app: manjorno-orders
    spec:
      containers:
      - name: manjorno-orders
        image: manjorno1.azurecr.io/manjorno-orders
        imagePullPolicy: Always
        env:
        - name: KEYCLOAK_URL
          value: http://20.90.169.171:8080/auth
        - name: KEYCLOAK_USERNAME
          valueFrom:
            secretKeyRef:
              name: manjorno-orders-secret
              key: keycloak_username
              optional: false
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: manjorno-orders-secret
              key: keycloak_password
              optional: false
        - name : KEYCLOAK_CLIENTCLI_SECRET
          valueFrom:
            secretKeyRef:
              name: manjorno-orders-secret
              key: keycloak_client_cli_secret
              optional: false
        - name: MONGODB_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: manjorno-orders-secret
              key: mongodb_connection_url
              optional: false
        - name: AMQP_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: manjorno-orders-secret
              key: amqp_connection_url
              optional: false
        - name: AMQP_EXCHANGE_USERS
          value: user
        - name: AMQP_EXCHANGE_RESTAURANTS
          value: restaurant
        - name: AMQP_EXCHANGE_EMPLOYEES
          value: employee
        - name: AMQP_EXCHANGE_MENUITEM
          value: menuItem
        ports:
        - containerPort: 3300

---


apiVersion: v1
kind: Service
metadata:
  name: manjorno-orders
spec:
  selector:
    app: manjorno-orders
  ports:
  - port: 3300
    targetPort: 3300