apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: order-microservice-ingress
  namespace: manjorno-orders
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /api/orders
        pathType: Prefix
        backend:
          service:
            name: manjorno-orders
            port:
              number: 3200